<div class="menu">
<h2>Mon menu du lundi 18/11 au vendredi 22/11</h2>

<div class="form-group">
    <div class="row col">
        Entrée
    </div>
    
    <div class="row">

</div>
    
</div>

<div class="input-group">
  <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
  <div class="input-group-append">
  <span class="input-group-text">3.00€</span>  
  <span class="input-group-text"><i class="fas fa-pencil-alt" onclick='';></i></span>
    
  </div>
</div>


<div class="input-group mb-3">
  <div class="input-group-prepend align-middle">
    <span class="input-group-text" id="inputGroup-sizing-default">Plat</span>
  </div>
  <input type="text" id="plat" value="dhaal lentilles" disabled class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
  <i class="fas fa-pencil-alt" onclick='';></i>
</div>

<div class="input-group mb-3">
  <div class="input-group-prepend align-middle">
    <span class="input-group-text" id="inputGroup-sizing-default">Dessert</span>
  </div>
  <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
  <i class="fas fa-pencil-alt"></i>
</div>

<hr />

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">€</span>
  </div>
  <input type="text" class="form-control" aria-label="Prix du menu">
  <div class="input-group-append">
    <span class="input-group-text">.00</span>
  </div>
</div>

</menu>
