<div class="row">
    <div class="col-6 text-right">
        <span class="count">13</span> boîtes en stock        
    </div>
    <div class="col-6 text-left">
        <span class="count">173</span> boîtes utilisées jusque là
    </div>
    </div>
    <div class="row">
        <div class="col-6 text-right">
            4 commandes en cours  <i class="fas fa-eye"></i>
        </div>
    </div>
<div class="commandes">
    <div class="card">
  <div class="card-header">
  Commande #4534 - Antoine Chassande - Amadeus
  </div>
  <div class="card-body">
    <h5 class="card-title">Plat du jour - 10€</h5>
    <p class="card-text">
        Amadeus - Bâtiment B
    </p>
    <a href="#" class="btn btn-primary">Valider commande</a>
  </div>
</div>
</div>


